Feature/task 2
ozonva/ova-exam-api pull request #3
Opened 2021-08-10 19:25 UTC by nefformat

2021-08-11 12:43 UTC, MrDniwe requested changes
Нужно переписать функцию фильтрации в соответствии с заданием, в остальном всё ок

2021-08-11 12:43 UTC, MrDniwe commented on cmd/ova-exam-api/internal/utils.go
> +	}
Пока ок, но на будущее - паника довольно редко используется в коде, её неудобно обрабатывать когда у тебя много горутин. И она недостаточно дескриптивна, особенно когда кода много. Гораздо более распространено возвращение ошибки отдельным значением.

2021-08-11 12:43 UTC, MrDniwe commented on cmd/ova-exam-api/internal/utils.go
> +	result := make(map[string]string, len(input))
Указывать длину мапы смысла особого не имеет, можно обойтись `make(map[string]string)`

2021-08-11 12:43 UTC, MrDniwe commented on cmd/ova-exam-api/internal/utils.go
> +}
Кажется там по условию список фильтруется не по одному значению, а тоже по списку значений. 

> Фильтрация по захордкоженному списку - нужно отфильтровать входной слайс по критерию отсутствия элемента в захардкоженном списке

2021-08-11 17:55 UTC, nefformat commented on cmd/ova-exam-api/internal/utils.go
> +	}
В задании написано что в любой непонятной ситуации кидай панику. 
А так да, я понимаю, что панику использовать не особо принято.

2021-08-11 17:57 UTC, nefformat commented on cmd/ova-exam-api/internal/utils.go
> +}
Переписал задание, добавил список внутрь функции.

2021-08-12 10:21 UTC, MrDniwe requested changes

2021-08-12 10:21 UTC, MrDniwe commented on cmd/ova-exam-api/internal/utils.go
> +	}
Работать будет, но по скорости это О(n*m), то есть при достаточно больших размерах фильтра и входящих данных будет стремиться куда-то в сторону O(n^2). Предлагаю фильтр преобразовать в map и получить таким образом O(n)

2021-08-12 15:05 UTC, nefformat commented on cmd/ova-exam-api/internal/utils.go
> +	}
переписал на использование map

2021-08-13 08:24 UTC, MrDniwe approved these changes
Всё ок!

2021-08-13 13:37 UTC, merged