Initial commit
ozonva/ova-exam-api pull request #4
Opened 2021-08-13 14:54 UTC by nefformat

2021-08-16 09:19 UTC, MrDniwe requested changes
Думаю нужно переделать структуру проекта

2021-08-16 09:19 UTC, MrDniwe commented on cmd/ova-exam-api/main.go
> +	fileName := pwd + "\\cmd\\ova-exam-api\\Makefile"
Вот с этим надо что-то делать. Лично у меня проект в таком виде не запускается. 

Во-первых, странный формат оказания пути сам по себе - двойные обратные слеши, хотя Go работает с обычными одинарными слешами, ну типа "cmd/ova-exam-api/Makefile". 

Во-вторых, для работы с путями рекомендую использовать https://pkg.go.dev/path - стандартный модуль для безопасной работы с путями.

В-третьих,  предлагаю следовать более канонической для Go структуры проекта: в корне репозитория лежат всяческие настроечные файлы: Makefile, go.mod, go.sum, .gitlab-ci.yaml и прочие yaml, конфиги, итд. Отсюда и происходит запуск проекта. Так же в корне лежат папки:
- cmd -  для компилируемых файлов (то есть main.go например)
- internal - для всех пакетов, имеющих отношение только к функционалу этого проекта (бизнес-логика в основном)
- pkg - для всех пакетов, которые могут быть переиспользованы в других проектах (экспортируемые интерфейсы, клиенты, итд)
- api - для описания API, например контрактов .proto
- bin - для скомпилированных бинарников используемых в проекте - например кодогенераторов, линтеров, итд. Обычно добавляется в .gitignore

То есть фактически нужно Makefile перенести в корень и сделать так чтобы `make run` успешно запускал `cmd/main.go`, или вроде того.

2021-08-16 17:32 UTC, nefformat commented on cmd/ova-exam-api/main.go
> +	fileName := pwd + "\\cmd\\ova-exam-api\\Makefile"
1. У меня на компьютере Windows возможно связанно с этим, если нужно тестировать для различных ОС, желательно об этом сообщить :) 
2. Использовал, надеюсь это решит проблему из пункта 1.
3. Создал описанную структуру директорий. Удалил лишний уровень вложенности c названием проекта внутри папки cmd (в задании после первого занятия было указание о необходимости создания данной директории).

2021-08-17 08:23 UTC, MrDniwe approved these changes
Ок, так гораздо лучше!

2021-08-17 11:45 UTC, merged