Task 4 init
ozonva/ova-exam-api pull request #5
Opened 2021-08-23 16:00 UTC by nefformat

2021-08-23 20:09 UTC, MrDniwe requested changes
Вцелом всё ок, но!
Есть пара вещей, которые хотелось бы:
1. Хотелось бы чтоб из корня проекта можно было бы сгенерировать моки командой `make generate-mocks` - это довольно регулярная задача в реальных проектах. Аналогично нужна команда `make test` которая запускает из корня проекта все его тесты.
2. Должен был заметить в прошлом МР-е, но видать был не очень внимателен: в `domain/entity` всё слишком разбито по отдельным модулям, в связи с чем присутствует круговая зависимость: answer ссылается на question, и обратно. Я думаю, не стоит так мудрить с подпапками, достаточно собрать всё в одном файле entity.

2021-08-23 20:09 UTC, MrDniwe commented on internal/mockgen.go
> +package internal
Не понял назначение этого файла. Без него никак?

2021-08-24 15:25 UTC, nefformat commented on internal/mockgen.go
> +package internal
У меня без него моки не генерируются. 
Если можно без него, то хотелось бы узнать как? Ну или получить ссылочку где можно об этом узнать

2021-08-24 15:26 UTC, nefformat commented
1. Добавил информацию по вызову test и generate-mocks в Makefile
2. Удалили лишние сущности

2021-08-25 13:12 UTC, MrDniwe approved these changes
Всё ок!

2021-08-25 13:12 UTC, MrDniwe commented on internal/mockgen.go
> +package internal
Я разобрался, в этом мок-генераторе сей файл вроде конфига. Я просто пользуюсь другим похожим, потому и удивился. Так-то всё ок.

2021-08-25 13:26 UTC, merged