Feature/task 5
ozonva/ova-exam-api pull request #6
Opened 2021-08-23 18:24 UTC by nefformat

2021-08-23 20:31 UTC, MrDniwe requested changes
В целом ок! Можно было бы конечно решить элегантнее через каналы и без мьютексов, но я не в курсе входит ли это в данный этап обучения. Осталось придумать поведение при переполнении и можно мержить.

2021-08-23 20:31 UTC, MrDniwe commented on internal/saver/saver.go
> +	}
Если кол-во сохраненных меньше вместимости, то выходим. А если не меньше... то тоже выходим. Каков скрытый смысл?)

2021-08-23 20:31 UTC, MrDniwe commented on internal/saver/saver.go
> +	}
Предлагаю при переполнении буфера делать принудительный слив во flusher

2021-08-24 16:16 UTC, nefformat commented on internal/saver/saver.go
> +	}
Замылился глаз под вечер, там и был код который отвечал за принудительный Flush при переполнении.
Вернул его на место.

2021-08-25 13:14 UTC, MrDniwe approved these changes
Всё ок!

2021-08-25 13:27 UTC, merged